### ISSUE TITLE
Errors with AbstractSite response processing in Python 3

### ISSUE THREAD

**Issue by voutilad** [freelawproject/juriscraper#174]
Reported over Slack by @arderyp using Python 3.5:

```
$ ./arderyp_test.p3.py live

Processing Court LIVE:    juriscraper.opinions.united_states.state.haw
scraping:        http://www.courts.state.hi.us/opinions_and_orders/opinions?yr=2017
E
======================================================================
ERROR: test_live (__main__.Arderyp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./arderyp_test.p3.py", line 308, in test_live
    self.run_scraper(package, output=output)
  File "./arderyp_test.p3.py", line 334, in run_scraper
    scraper.parse()
  File "/home/arderyp/code/git/juriscraper/juriscraper/AbstractSite.py", line 101, in parse
    self.html = self._download()
  File "/home/arderyp/code/git/juriscraper/juriscraper/opinions/united_states/state/haw.py", line 21, in _download
    html = super(Site, self)._download(request_dict)
  File "/home/arderyp/code/git/juriscraper/juriscraper/AbstractSite.py", line 290, in _download
    return self._return_request_text_object()
  File "/home/arderyp/code/git/juriscraper/juriscraper/AbstractSite.py", line 345, in _return_request_text_object
    text = self._clean_text(payload)
  File "/home/arderyp/code/git/juriscraper/juriscraper/AbstractSite.py", line 129, in _clean_text
    return clean_html(text)
  File "/home/arderyp/code/git/juriscraper/juriscraper/lib/html_utils.py", line 97, in clean_html
    text = re.sub(r'<!\[CDATA\[', u'', text)
  File "/home/arderyp/.virtualenvs/juriscraper3/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

----------------------------------------------------------------------
Ran 1 test in 2.813s

FAILED (errors=1)
```

**Comment by flooie** [comment]
This should certainly be resolved because we are now py3.
