### ISSUE TITLE
slowness errors when running tests

### ISSUE THREAD

**Issue by umeboshi2** [freelawproject/juriscraper#242]
I just started running the tests provided.  I got these errors.  I noticed that a previous issue (#18) discusses failing tests for slowness.  What should be done about this?

```
======================================================================
ERROR: test_scrape_all_example_files (tests.test_everything.ScraperExampleTest)
Finds all the $module_example* files and tests them with the sample
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/freespace/home/umeboshi/.virtualenvs/juriscraper-py2/local/lib/python2.7/site-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/freespace/home/umeboshi/.virtualenvs/juriscraper-py2/local/lib/python2.7/site-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/freespace/home/umeboshi/.virtualenvs/juriscraper-py2/local/lib/python2.7/site-packages/vcr/cassette.py", line 148, in _handle_function
    return fn(cassette)
  File "/freespace/home/umeboshi/.virtualenvs/juriscraper-py2/local/lib/python2.7/site-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/tests/test_everything.py", line 212, in test_scrape_all_example_files
    warning_msg = warn_or_crash_slow_parser(t2 - t1)
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/juriscraper/lib/test_utils.py", line 58, in warn_or_crash_slow_parser
    max_duration=max_duration)
SlownessException: This scraper took 16.8416581154s to test, which is more than the allowed speed of 15s. Please speed it up for tests to pass.

======================================================================
ERROR: test_bankruptcy_court_dockets (tests.test_pacer.DocketParseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/tests/test_pacer.py", line 817, in test_bankruptcy_court_dockets
    self.run_parsers_on_path(path_root)
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/tests/test_pacer.py", line 811, in run_parsers_on_path
    warn_or_crash_slow_parser(duration, max_duration=1)
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/juriscraper/lib/test_utils.py", line 58, in warn_or_crash_slow_parser
    max_duration=max_duration)
SlownessException: This scraper took 1.16746807098s to test, which is more than the allowed speed of 1s. Please speed it up for tests to pass.

======================================================================
ERROR: test_district_court_dockets (tests.test_pacer.DocketParseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/tests/test_pacer.py", line 822, in test_district_court_dockets
    self.run_parsers_on_path(path_root)
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/tests/test_pacer.py", line 811, in run_parsers_on_path
    warn_or_crash_slow_parser(duration, max_duration=1)
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/juriscraper/lib/test_utils.py", line 58, in warn_or_crash_slow_parser
    max_duration=max_duration)
SlownessException: This scraper took 1.11986112595s to test, which is more than the allowed speed of 1s. Please speed it up for tests to pass.

======================================================================
ERROR: test_parsing_history_documents (tests.test_pacer.PacerDocketHistoryReportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/tests/test_pacer.py", line 610, in test_parsing_history_documents
    self.parse_files(path_root, '*.html', DocketHistoryReport)
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/tests/test_pacer.py", line 569, in parse_files
    warn_or_crash_slow_parser(duration, max_duration=2)
  File "/freespace/home/umeboshi/workspace/freelaw/freelawmachine/juriscraper/juriscraper/lib/test_utils.py", line 58, in warn_or_crash_slow_parser
    max_duration=max_duration)
SlownessException: This scraper took 2.38739514351s to test, which is more than the allowed speed of 2s. Please speed it up for tests to pass.

----------------------------------------------------------------------
Ran 70 tests in 197.571s

FAILED (errors=4, skipped=13)
Test failed: <unittest.runner.TextTestResult run=70 errors=4 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=70 errors=4 failures=0>
```

**Comment by mlissner** [comment]
I guess there's three approaches here:

1. Get a faster computer or network connection.

2. Dig into the code to figure out why its too slow. The purpose of the tests is to make sure that we don't have any *really* big HTML that we're parsing or *really* slow XPath queries. Usually if a test fails it's because of the HTML and the easiest fix is to edit the test HTML to make it smaller and thus faster. 

3. Disable the slowness tests (they're disabled during continuous integration, for example).

**Comment by arderyp** [comment]
regarding your second point @mlissner, some really slow scraper tests are the result of the said tests making live network requests.  I've cleaned up multiple tests that were doing this, and there may be more out there.  This would be the first thing I'd look into (run test for specific scraper with wifi/ethernet disabled).

**Comment by umeboshi2** [comment]
I chose to just disable the slowness tests entirely, similar to how travis environment is detected.  I'm sending a PR your way.  Since y'all seem to be using this internally, would it be better to set a "TEST_SLOWNESS" environment variable to enable these tests and just emit a warning, or ignore completely by default?

**Comment by mlissner** [comment]
I wouldn't want to ignore them completely because they do force us to make things faster. At the same time, I don't want to bug people with them. I guess that means they should just emit warnings as a middle ground.

**Comment by umeboshi2** [comment]
@arderyp, it looks like ```juriscraper.opinions.united_states.state.coloctapp``` may be accessing the network.  Just working on PR, so I haven't had time to take a good look, just noticed network usage when performing test.

All tests pass when slowness check is disabled.  :)

**Comment by arderyp** [comment]
yeahhhhh, colo is just a disastrous site with a disastrous scraper.  Avoiding network connections during tests of colo/coloctapp might be difficult given the current test infrastructure.  See: https://github.com/freelawproject/juriscraper/blob/master/juriscraper/opinions/united_states/state/colo.py#L42-L45
