### ISSUE TITLE
 Blocked scraper: opinions.united_states.state.nm(ctapp)

### ISSUE THREAD

**Issue by arderyp** [freelawproject/juriscraper#258]
These scrapers work on my machine, and thr urls work via curl from my machine:

```
$ curl -I "https://nmonesource.com/nmos/nmca/en/nav_date.do?iframe=true"
HTTP/2 200 
date: Tue, 14 May 2019 02:49:08 GMT
content-type: text/html;charset=utf-8
server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
cache-control: max-age=0, no-cache

$ curl -I "https://nmonesource.com/nmos/nmsc/en/nav_date.do?iframe=true"
HTTP/2 200 
date: Tue, 14 May 2019 02:50:18 GMT
content-type: text/html;charset=utf-8
server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
cache-control: max-age=0, no-cache
```

And yet, both urls are returning 403 forbidden errors consistently in prod:

```
:
********!! CRAWLER DOWN !!***********
*****scrape_court method failed!*****
********!! ACTION NEEDED !!**********
Traceback (most recent call last):
File "/var/www/courtlistener/cl/scrapers/management/commands/cl_scrape_opinions.py", line 324, in handle
self.parse_and_scrape_site(mod, options['full_crawl'])
File "/var/www/courtlistener/cl/scrapers/management/commands/cl_scrape_opinions.py", line 289, in parse_and_scrape_site
site = mod.Site().parse()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 112, in parse
self.html = self._download()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/opinions/united_states/state/nm.py", line 51, in _download
html = super(Site, self)._download(self.request_dict)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 303, in _download
self._post_process_response()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 356, in _post_process_response
self.request['response'].raise_for_status()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: 403 for url: https://nmonesource.com/nmos/nmsc/en/nav_date.do?iframe=true
```

```
********!! CRAWLER DOWN !!***********
*****scrape_court method failed!*****
********!! ACTION NEEDED !!**********
Traceback (most recent call last):
File "/var/www/courtlistener/cl/scrapers/management/commands/cl_scrape_opinions.py", line 324, in handle
self.parse_and_scrape_site(mod, options['full_crawl'])
File "/var/www/courtlistener/cl/scrapers/management/commands/cl_scrape_opinions.py", line 289, in parse_and_scrape_site
site = mod.Site().parse()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 112, in parse
self.html = self._download()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/opinions/united_states/state/nm.py", line 51, in _download
html = super(Site, self)._download(self.request_dict)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 303, in _download
self._post_process_response()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 356, in _post_process_response
self.request['response'].raise_for_status()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: 403 for url: https://nmonesource.com/nmos/nmca/en/nav_date.do?iframe=true
```

I'm guessing that resolving this will require calling the court.  Unfortunately, I don't have the bandwidth to take care of that at this time.

**Comment by mlissner** [comment]
Just checked on prod:

```
↪ curl -I "https://nmonesource.com/nmos/nmsc/en/nav_date.do?iframe=true"
HTTP/1.1 403 403
Date: Tue, 14 May 2019 16:52:28 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 3110
Connection: keep-alive
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Cache-Control: private,no-cache,no-store
Pragma: No-cache
Set-Cookie: decisia-logged-locale-prod-site=en; Domain=nmonesource.com; Path=/; HttpOnly
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Language: en
```

I guess a phone call is in order here.

**Comment by flooie** [comment]
```
HTTP/1.1 200 200
Date: Sat, 28 Jan 2023 14:22:22 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 37624
Connection: keep-alive
Server: Apache
Strict-Transport-Security: max-age=63072000; includeSubDomains
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Frame-Options: SAMEORIGIN
Content-Language: en
```

looks all good to me.
