### ISSUE TITLE
 Blocked scraper: opinions.united_states.state.ky

### ISSUE THREAD

**Issue by arderyp** [freelawproject/juriscraper#261]
Scraper works slowly on my machine, but have been timing out in production for months now.  I'm suspicious that the court may be blocking our production IP. 

Need to call the court.

```
********!! CRAWLER DOWN !!***********
*****scrape_court method failed!*****
********!! ACTION NEEDED !!**********
Traceback (most recent call last):
File "/var/www/courtlistener/cl/scrapers/management/commands/cl_scrape_opinions.py", line 324, in handle
self.parse_and_scrape_site(mod, options['full_crawl'])
File "/var/www/courtlistener/cl/scrapers/management/commands/cl_scrape_opinions.py", line 289, in parse_and_scrape_site
site = mod.Site().parse()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 112, in parse
self.html = self._download()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/opinions/united_states/state/ky.py", line 105, in _download
html = super(Site, self)._download(request_dict)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 300, in _download
self._request_url_post(self.url)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 345, in _request_url_post
**self.request['parameters']
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/sessions.py", line 572, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
resp = self.send(prep, **send_kwargs)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
r = adapter.send(request, **kwargs)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='162.114.92.72', port=80): Max retries exceeded with url: /dtSearch/dtisapi6.dll (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f288e317ad0>, 'Connection to 162.114.92.72 timed out. (connect timeout=60)'))
```

**Comment by arderyp** [comment]
You asked for the url to test against via curl.  It's too complicated for me to comment here.  Its a big post request.  See this: https://github.com/freelawproject/juriscraper/blob/master/juriscraper/opinions/united_states/state/ky.py#L74-L100

**Comment by arderyp** [comment]
UPDATE: This scraper is now failing in dev during `_fetch_case_name()`.  The sub-request is triggering a 500 error [here](https://github.com/freelawproject/juriscraper/blob/master/juriscraper/opinions/united_states/state/ky.py#L181).

The sub-requests is a POST to http://162.114.92.78/dockets/SearchCaseDetail.asp.  

The web interface for this search is http://162.114.92.78/dockets/SearchbyCaseNumber.htm

I have no idea if this is a production service (it doesn't look like it, but that doesn't necessarily mean anything).  I have no idea if it is linked to from anywhere else on the KY court site(s), and I have no idea how we actually found out about this widget (before my time).  But, it appears to be broken now.  I will contact the court to solicit assistance, but they've historically been unhelpful/non-responsive to past requests.

**Comment by mlissner** [comment]
Thanks @arderyp. I appreciate you following up on this one. Looking at the comment here: https://github.com/freelawproject/juriscraper/blob/master/juriscraper/opinions/united_states/state/ky.py#L75-L79, it seems like it's fairly easy to get a handle on the new URL. Right now it's set to: 

http://162.114.92.72/dtSearch/dtisapi6.dll

Tried that?

**Comment by arderyp** [comment]
That url isn't the problem.  Our initial post to that url works just fine.  The problem is with the sub-query post we have to make to fetch case names, as explained in my comment above.

**Comment by arderyp** [comment]
@mlissner that url you mentioned is not the problem. Our initial post to that url works just fine. The problem is with the sub-query post we have to make to fetch case names, as explained in my comment above.

**Comment by arderyp** [comment]
@mlissner I should clarify.  The url you mentioned is not the (new) problem _in dev_.  However, the logs suggest that the url you mentioned _may be_ blocking our prod instance, which is what this issue was originally about.

**Comment by mlissner** [comment]
OK, I'm striking out over on #262, but I think for this one, the missing URL is here:

https://appellate.kycourts.net/SC/SCDockets/

That shows the form that you can use to look up the case name and other metadata for a given case.

**Comment by arderyp** [comment]
hmmm, maybe they moved it.  I will look into that later.

**Comment by arderyp** [comment]
@mlissner the latest commit fixes the scraper so it now runs in dev.  But the PROD log still indicates that we are likely being blocked:

```

********!! CRAWLER DOWN !!***********
*****scrape_court method failed!*****
********!! ACTION NEEDED !!**********
Traceback (most recent call last):
File "/var/www/courtlistener/cl/scrapers/management/commands/cl_scrape_opinions.py", line 324, in handle
self.parse_and_scrape_site(mod, options['full_crawl'])
File "/var/www/courtlistener/cl/scrapers/management/commands/cl_scrape_opinions.py", line 289, in parse_and_scrape_site
site = mod.Site().parse()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 112, in parse
self.html = self._download()
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/opinions/united_states/state/ky.py", line 105, in _download
html = super(Site, self)._download(request_dict)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 300, in _download
self._request_url_post(self.url)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/juriscraper/AbstractSite.py", line 345, in _request_url_post
**self.request['parameters']
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/sessions.py", line 572, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
resp = self.send(prep, **send_kwargs)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
r = adapter.send(request, **kwargs)
File "/var/www/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='162.114.92.72', port=80): Max retries exceeded with url: /dtSearch/dtisapi6.dll (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f441c378d90>, 'Connection to 162.114.92.72 timed out. (connect timeout=60)'))
```

You can experiment with posting via cURL on the command line to see if maybe they are restricting by our `User-Agent`.  If it works from your machine with and without our UA, you will probably need to jump onto the PROD server and do some cURL test there.

**Comment by mlissner** [comment]
OK, yes, you've been right all along, thank you. It works fine locally when I do these commands:

```
curl 162.114.92.72
curl https://appellate.kycourts.net/SC/SCDockets/ --insecure
```
(Though it requires `--insecure` because their SSL is screwy.)

But when I do the same on the server, it just sits there stalled. I'll try to give them a call.

**Comment by mlissner** [comment]
Left a voicemail for their information officer. She's reachable via the AO: 502-573-2350.

**Comment by arderyp** [comment]
@mlissner goooooooood luck!

The only time they have ever responded to any contact I've made (maybe 1 our of 8 attempts), they were rather combative about the issue.  Not only do they not want to help us, but they view us as a nuisance (hence the blocking).  Did you try on PROD both with/without our UA?  In other words, are you sure they are blocking the actual IP?

**Comment by arderyp** [comment]
if she ever responds, it might be worth adding her name and phone number to to scraper file

**Comment by mlissner** [comment]
I tried with the same UA on my laptop and on prod. I'll definitely add her name to a file if I can get through to her.

**Comment by arderyp** [comment]
ooof, of course the UA isn't the issue if it works on my machine with that UA... lol, long morning, sorry.

**Comment by mlissner** [comment]
Heard back from Jamie Neal. She's going to forward an email on my behalf. We'll see.

**Comment by flooie** [comment]
Appears unblocked after fixes 

<img width="715" alt="Screenshot 2023-11-21 at 12 02 04 PM" src="https://github.com/freelawproject/juriscraper/assets/6464529/9ec52028-6081-4e3c-84b1-fd347334dd02">
