### ISSUE TITLE
Fix scraper PACER Free Opinions

### ISSUE THREAD

**Issue by satsuki-chan** [freelawproject/juriscraper#418]
PACER Free Opinions fails while scraping opinions from the **Middle District of Louisiana**.

```
INFO Attempting to get latest document references for lamb between 2021-08-02 and 2021-08-09
Traceback (most recent call last):
File "/opt/courtlistener/manage.py", line 15, in <module>
main()
File "/opt/courtlistener/manage.py", line 11, in main
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
output = self.handle(*args, **options)
File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 302, in handle
action(options)
File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 259, in do_everything
get_and_save_free_document_reports(options)
File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 135, in get_and_save_free_document_reports
status = get_and_save_free_document_report(
File "/usr/local/lib/python3.8/site-packages/celery/local.py", line 191, in __call__
return self._get_current_object()(*a, **kw)
File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 393, in __call__
return self.run(*args, **kwargs)
File "/opt/courtlistener/cl/corpus_importer/tasks.py", line 317, in get_and_save_free_document_report
report.query(start, end, sort="case_number")
File "/usr/local/lib/python3.8/site-packages/juriscraper/pacer/free_documents.py", line 82, in query
nonce = get_nonce_from_form(response)
File "/usr/local/lib/python3.8/site-packages/juriscraper/pacer/utils.py", line 200, in get_nonce_from_form
tree = html.fromstring(r.text)
File "/usr/local/lib/python3.8/site-packages/lxml/html/__init__.py", line 875, in fromstring
doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
File "/usr/local/lib/python3.8/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
value = etree.fromstring(html, parser, **kw)
File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
File "src/lxml/parser.pxi", line 1891, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

**Comment by satsuki-chan** [comment]
From the CourtListener server, the calls to the PACER server for Louisiana were blocked:

```
In [25]: simple_r = requests.get('https://ecf.lamb.uscourts.gov/cgi-bin/WrtOpRpt.pl')

In [26]: simple_r.status_code
Out[26]: 404

In [27]: print(simple_r.text)
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Object not found!</title>
<link rev="made" href="mailto:root@www" />
<style type="text/css"><!--/*--><![CDATA[/*><!--*/ 
    body { color: #000000; background-color: #FFFFFF; }
    a:link { color: #0000CC; }
    p, address {margin-left: 3em;}
    span {font-size: smaller;}
/*]]>*/--></style>
</head>

<body>
<h1>Object not found!</h1>
<p>


    The requested URL was not found on this server.

  

    If you entered the URL manually please check your
    spelling and try again.

  

</p>
<p>
</p>

<h2>Error 404</h2>
<address>
 
  
</address>
</body>
</html>
```

**Comment by mlissner** [comment]
Auto-closed, but we still need the CL side of this.

**Comment by mlissner** [comment]
Auto-closed, but there's one more piece of this we should do. :) 

@satsuki-chan, this bug is giving you a tour through the code. I just released version 2.3.19 of Juriscraper so we can land these changes. Can you take a look in CourtListener and see if its pyproject.toml file needs any updates to get the latest Juriscraper?

**Comment by satsuki-chan** [comment]
CourtListener asks for version **2.3.0** (or higher) of Juriscraper in its `pyproject.toml` file:
```
[tool.poetry.dependencies]
...
juriscraper = "^2.3.0"
```

Should I make a change to file `pyproject.toml` to require at least version **2.3.19** @mlissner  ?

**Comment by mlissner** [comment]
That's great, so I think somebody just needs to build and push new docker images. I'll put that on my list for today.

**Comment by mlissner** [comment]
And this is pushed, but we got a fresh stack trace from last night's crawl, so something still isn't quite working:

```
INFO Got all document references for 'flmb'.
INFO Attempting to get latest document references for flnb between 2021-11-18 and 2021-11-23
--- Logging error ---
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/juriscraper/pacer/utils.py", line 213, in get_nonce_from_form
path, nonce = attr.split("?")
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/courtlistener/cl/corpus_importer/tasks.py", line 317, in get_and_save_free_document_report
report.query(start, end, sort="case_number")
File "/usr/local/lib/python3.8/site-packages/juriscraper/pacer/free_documents.py", line 80, in query
nonce = get_nonce_from_form(response)
File "/usr/local/lib/python3.8/site-packages/juriscraper/pacer/utils.py", line 215, in get_nonce_from_form
raise ParsingException("Didn't get nonce from PACER form.")
juriscraper.lib.exceptions.ParsingException: Didn't get nonce from PACER form.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/logging/__init__.py", line 1081, in emit
msg = self.format(record)
File "/usr/local/lib/python3.8/logging/__init__.py", line 925, in format
return fmt.format(record)
File "/usr/local/lib/python3.8/logging/__init__.py", line 664, in format
record.message = record.getMessage()
File "/usr/local/lib/python3.8/logging/__init__.py", line 369, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
File "/opt/courtlistener/manage.py", line 15, in <module>
main()
File "/opt/courtlistener/manage.py", line 11, in main
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
output = self.handle(*args, **options)
File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 302, in handle
action(options)
File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 259, in do_everything
get_and_save_free_document_reports(options)
File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 135, in get_and_save_free_document_reports
status = get_and_save_free_document_report(
File "/usr/local/lib/python3.8/site-packages/celery/local.py", line 191, in __call__
return self._get_current_object()(*a, **kw)
File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 393, in __call__
return self.run(*args, **kwargs)
File "/opt/courtlistener/cl/corpus_importer/tasks.py", line 351, in get_and_save_free_document_report
http://logger.info(f"{msg} Retrying.", court_id, start, end)
File "/usr/local/lib/python3.8/logging/__init__.py", line 1434, in info
self._log(INFO, msg, args, **kwargs)
File "/usr/local/lib/python3.8/logging/__init__.py", line 1577, in _log
self.handle(record)
File "/usr/local/lib/python3.8/logging/__init__.py", line 1587, in handle
self.callHandlers(record)
File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/logging.py", line 85, in sentry_patched_callhandlers
return old_callhandlers(self, record)
Message: "Didn't get Nonce Retrying."
Arguments: ('flnb', datetime.date(2021, 11, 18), datetime.date(2021, 11, 23))
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/juriscraper/pacer/utils.py", line 213, in get_nonce_from_form
path, nonce = attr.split("?")
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/courtlistener/manage.py", line 15, in <module>
main()
File "/opt/courtlistener/manage.py", line 11, in main
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
output = self.handle(*args, **options)
File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 302, in handle
action(options)
File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 259, in do_everything
get_and_save_free_document_reports(options)
File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 135, in get_and_save_free_document_reports
status = get_and_save_free_document_report(
File "/usr/local/lib/python3.8/site-packages/celery/local.py", line 191, in __call__
return self._get_current_object()(*a, **kw)
File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 393, in __call__
return self.run(*args, **kwargs)
File "/opt/courtlistener/cl/corpus_importer/tasks.py", line 352, in get_and_save_free_document_report
raise self.retry(exc=exc, countdown=5)
File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 690, in retry
raise_with_context(exc or Retry('Task can be retried', None))
File "/opt/courtlistener/cl/corpus_importer/tasks.py", line 317, in get_and_save_free_document_report
report.query(start, end, sort="case_number")
File "/usr/local/lib/python3.8/site-packages/juriscraper/pacer/free_documents.py", line 80, in query
nonce = get_nonce_from_form(response)
File "/usr/local/lib/python3.8/site-packages/juriscraper/pacer/utils.py", line 215, in get_nonce_from_form
raise ParsingException("Didn't get nonce from PACER form.")
juriscraper.lib.exceptions.ParsingException: Didn't get nonce from PACER form.
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by satsuki-chan** [comment]
Added PR with correction manage ValueError exeptions, like the ona that ocurred while scraping opinions from the **District Court for the Northern District of Florida** (flnb).
