### ISSUE TITLE
Free Opinion Scraper Down

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#509]
I haven't had a good opportunity to look at this yet, but we're getting this crash at the end of our free opinion scrapes:

```
docker exec --user www-data cl-python /opt/courtlistener/manage.py scrape_pacer_free_opinions --traceback --action do-everything --queue='batch2' --index
INFO Running and compiling free document reports.
INFO Attempting to get latest document references for cofc between 2022-04-07 and 2022-04-12
INFO Got all document references for 'cofc'.
INFO Attempting to get latest document references for cit between 2022-04-07 and 2022-04-12
INFO Got all document references for 'cit'.
INFO Attempting to get latest document references for almb between 2022-04-07 and 2022-04-12
INFO Got all document references for 'almb'.
INFO Attempting to get latest document references for alnb between 2022-04-07 and 2022-04-12
INFO Got all document references for 'alnb'.

[ ----- 8< ----- a few hundred more lines like this -------------8<-----]

INFO Got all document references for 'deb'.
INFO Getting PDFs from free document reports
INFO downloading and indexing 87948 items from PACER.
Traceback (most recent call last):
  File "/opt/courtlistener/manage.py", line 15, in <module>
    main()
  File "/opt/courtlistener/manage.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 304, in handle
    action(options)
  File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 263, in do_everything
    get_pdfs(options)
  File "/opt/courtlistener/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py", line 226, in get_pdfs
    c.apply_async()
  File "/usr/local/lib/python3.10/site-packages/celery/canvas.py", line 643, in apply_async
    app = [self.app](http://self.app/)
  File "/usr/local/lib/python3.10/site-packages/celery/canvas.py", line 822, in app
    app = self.tasks[0]._app
TypeError: 'NoneType' object is not subscriptable
```

Alberto, if you could take a look at this and see what you see, that'd be great. I'm not familiar with this error, but it looks like Celery isn't happy for some reason. Let me know if you want to chat about this issue to understand it better.

While this is down, we're not getting our free opinions from PACER.

**Comment by mlissner** [comment]
Fixed via https://github.com/freelawproject/courtlistener/pull/2017
