### ISSUE TITLE
Move Phantomjs to a single import and single instance

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#74]
I'm pretty sure most of the reason that PhantomJS is slow is because we import and instantiate it every single time. A better solution would keep it around after it was started each time. An even better solution would keep it around, but only instantiate it when it was first needed (so calling just one scraper that doesn't use Phantomjs isn't negatively impacted).

There's [an answer on StackOverflow that has some tips about this](http://stackoverflow.com/a/27691489/64911). This also might help with the Webdriver connection errors we seem to have on longer-running processes.

**Comment by mlissner** [comment]
Further investigation here has revealed a few things:

1. If you quit phantomjs and then try to quickly instantiate a new one, you're looking for pain. There's a 30s timer in the code that in theory makes this possible, since the old phantomjs doesn't go away immediately. But if 30s elapse and your old one is still around, the new one can't be created and then crashes your program. Why it's like this, I know not, but it's certainly annoying. It crashes with:

        Traceback (most recent call last):
          File "/var/www/court-listener/alert/scrapers/management/commands/cl_scrape_opinions.py", line 430, in handle
            self.parse_and_scrape_site(mod, full_crawl)
          File "/var/www/court-listener/alert/scrapers/management/commands/cl_back_scrape_opinions.py", line 11, in parse_and_scrape_site
            for site in site_yielder(mod.Site().back_scrape_iterable, mod):
          File "/usr/lib/python2.7/dist-packages/juriscraper/lib/importer.py", line 51, in site_yielder
            site._download_backwards(i)
          File "/usr/lib/python2.7/dist-packages/juriscraper/opinions/united_states/state/tex.py", line 237, in _download_backwards
            self.html = self._download()
          File "/usr/lib/python2.7/dist-packages/juriscraper/opinions/united_states/state/tex.py", line 56, in _download
            service_log_path=os.path.devnull,  # Disable ghostdriver.log
          File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 50, in __init__
            self.service.start()
          File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/phantomjs/service.py", line 69, in start
            raise WebDriverException("Can not connect to GhostDriver")
        WebDriverException: Message: 'Can not connect to GhostDriver'

2. The way we currently import modules means that there's no long-living object that persists between scrapes of one site and the next (or multiple scrapes of the same site, in the case of a backscraper). This means that we need to either load PhantomJS in the caller and pass it to the scraper (which sucks), or change Juriscraper's caller API. Current code works like this:

        module_strings = build_module_list(court_id)
        package, module = module_strings[i].rsplit('.', 1)
        mod = __import__("%s.%s" % (package, module),
                         globals(),
                         locals(),
                         [module])
        site = mod.Site()
        site.parse()

    A better approach would probably be to instantiate a new Juriscraper object that holds onto long-running stuff and does the wack-a-doo string conversion for you. Something like:

        j = Juriscraper()
        j.start()
        s = j.parse('tex')  # or j.parse('united_states.opinions'), or whatever.

    It's a much nicer API that moves the craziness out of the callers. What's more, it gives us a place where we can keep PhantomJS.

**Comment by mlissner** [comment]
Well, we moved past phantom to just using selenium, and now we might be removing that, so....closing!
